//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigoSoftware.NewYorkTimesServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestSeller", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.Services.NewYorkTimes")]
    [System.SerializableAttribute()]
    internal partial class BestSeller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsteriskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BestSellersDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.BookDetail> BookDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.BookReview> BookReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaggerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ISBN10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ISBN13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PublishedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankLastWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeeksOnListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Asterisk {
            get {
                return this.AsteriskField;
            }
            set {
                if ((object.ReferenceEquals(this.AsteriskField, value) != true)) {
                    this.AsteriskField = value;
                    this.RaisePropertyChanged("Asterisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime BestSellersDate {
            get {
                return this.BestSellersDateField;
            }
            set {
                if ((this.BestSellersDateField.Equals(value) != true)) {
                    this.BestSellersDateField = value;
                    this.RaisePropertyChanged("BestSellersDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.BookDetail> BookDetails {
            get {
                return this.BookDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookDetailsField, value) != true)) {
                    this.BookDetailsField = value;
                    this.RaisePropertyChanged("BookDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.BookReview> BookReviews {
            get {
                return this.BookReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookReviewsField, value) != true)) {
                    this.BookReviewsField = value;
                    this.RaisePropertyChanged("BookReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Dagger {
            get {
                return this.DaggerField;
            }
            set {
                if ((object.ReferenceEquals(this.DaggerField, value) != true)) {
                    this.DaggerField = value;
                    this.RaisePropertyChanged("Dagger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<string> ISBN10 {
            get {
                return this.ISBN10Field;
            }
            set {
                if ((object.ReferenceEquals(this.ISBN10Field, value) != true)) {
                    this.ISBN10Field = value;
                    this.RaisePropertyChanged("ISBN10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<string> ISBN13 {
            get {
                return this.ISBN13Field;
            }
            set {
                if ((object.ReferenceEquals(this.ISBN13Field, value) != true)) {
                    this.ISBN13Field = value;
                    this.RaisePropertyChanged("ISBN13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ListName {
            get {
                return this.ListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ListNameField, value) != true)) {
                    this.ListNameField = value;
                    this.RaisePropertyChanged("ListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime PublishedDate {
            get {
                return this.PublishedDateField;
            }
            set {
                if ((this.PublishedDateField.Equals(value) != true)) {
                    this.PublishedDateField = value;
                    this.RaisePropertyChanged("PublishedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RankLastWeek {
            get {
                return this.RankLastWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.RankLastWeekField, value) != true)) {
                    this.RankLastWeekField = value;
                    this.RaisePropertyChanged("RankLastWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string WeeksOnList {
            get {
                return this.WeeksOnListField;
            }
            set {
                if ((object.ReferenceEquals(this.WeeksOnListField, value) != true)) {
                    this.WeeksOnListField = value;
                    this.RaisePropertyChanged("WeeksOnList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookDetail", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.Services.NewYorkTimes")]
    [System.SerializableAttribute()]
    internal partial class BookDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContributorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContributorNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AgeGroup {
            get {
                return this.AgeGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeGroupField, value) != true)) {
                    this.AgeGroupField = value;
                    this.RaisePropertyChanged("AgeGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Contributor {
            get {
                return this.ContributorField;
            }
            set {
                if ((object.ReferenceEquals(this.ContributorField, value) != true)) {
                    this.ContributorField = value;
                    this.RaisePropertyChanged("Contributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ContributorNote {
            get {
                return this.ContributorNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.ContributorNoteField, value) != true)) {
                    this.ContributorNoteField = value;
                    this.RaisePropertyChanged("ContributorNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookReview", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.Services.NewYorkTimes")]
    [System.SerializableAttribute()]
    internal partial class BookReview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticleChapterLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookReviewLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstChapterLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SundayReviewLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ArticleChapterLink {
            get {
                return this.ArticleChapterLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticleChapterLinkField, value) != true)) {
                    this.ArticleChapterLinkField = value;
                    this.RaisePropertyChanged("ArticleChapterLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string BookReviewLink {
            get {
                return this.BookReviewLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.BookReviewLinkField, value) != true)) {
                    this.BookReviewLinkField = value;
                    this.RaisePropertyChanged("BookReviewLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FirstChapterLink {
            get {
                return this.FirstChapterLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstChapterLinkField, value) != true)) {
                    this.FirstChapterLinkField = value;
                    this.RaisePropertyChanged("FirstChapterLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SundayReviewLink {
            get {
                return this.SundayReviewLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.SundayReviewLinkField, value) != true)) {
                    this.SundayReviewLinkField = value;
                    this.RaisePropertyChanged("SundayReviewLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewsWire", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.Services.NewYorkTimes")]
    [System.SerializableAttribute()]
    internal partial class NewsWire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlogNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ByLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriesTagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexingTermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KickerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.Media> MediaItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubHeadlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string BlogName {
            get {
                return this.BlogNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogNameField, value) != true)) {
                    this.BlogNameField = value;
                    this.RaisePropertyChanged("BlogName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ByLine {
            get {
                return this.ByLineField;
            }
            set {
                if ((object.ReferenceEquals(this.ByLineField, value) != true)) {
                    this.ByLineField = value;
                    this.RaisePropertyChanged("ByLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CategoriesTags {
            get {
                return this.CategoriesTagsField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesTagsField, value) != true)) {
                    this.CategoriesTagsField = value;
                    this.RaisePropertyChanged("CategoriesTags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CopyRight {
            get {
                return this.CopyRightField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyRightField, value) != true)) {
                    this.CopyRightField = value;
                    this.RaisePropertyChanged("CopyRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Headline {
            get {
                return this.HeadlineField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadlineField, value) != true)) {
                    this.HeadlineField = value;
                    this.RaisePropertyChanged("Headline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IndexingTerms {
            get {
                return this.IndexingTermsField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexingTermsField, value) != true)) {
                    this.IndexingTermsField = value;
                    this.RaisePropertyChanged("IndexingTerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Kicker {
            get {
                return this.KickerField;
            }
            set {
                if ((object.ReferenceEquals(this.KickerField, value) != true)) {
                    this.KickerField = value;
                    this.RaisePropertyChanged("Kicker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.Media> MediaItems {
            get {
                return this.MediaItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaItemsField, value) != true)) {
                    this.MediaItemsField = value;
                    this.RaisePropertyChanged("MediaItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Organizations {
            get {
                return this.OrganizationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationsField, value) != true)) {
                    this.OrganizationsField = value;
                    this.RaisePropertyChanged("Organizations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string People {
            get {
                return this.PeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleField, value) != true)) {
                    this.PeopleField = value;
                    this.RaisePropertyChanged("People");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Platform {
            get {
                return this.PlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                    this.PlatformField = value;
                    this.RaisePropertyChanged("Platform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RelatedUrl {
            get {
                return this.RelatedUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedUrlField, value) != true)) {
                    this.RelatedUrlField = value;
                    this.RaisePropertyChanged("RelatedUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Section {
            get {
                return this.SectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionField, value) != true)) {
                    this.SectionField = value;
                    this.RaisePropertyChanged("Section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubHeadline {
            get {
                return this.SubHeadlineField;
            }
            set {
                if ((object.ReferenceEquals(this.SubHeadlineField, value) != true)) {
                    this.SubHeadlineField = value;
                    this.RaisePropertyChanged("SubHeadline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubSection {
            get {
                return this.SubSectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubSectionField, value) != true)) {
                    this.SubSectionField = value;
                    this.RaisePropertyChanged("SubSection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubType {
            get {
                return this.SubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypeField, value) != true)) {
                    this.SubTypeField = value;
                    this.RaisePropertyChanged("SubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Terms {
            get {
                return this.TermsField;
            }
            set {
                if ((object.ReferenceEquals(this.TermsField, value) != true)) {
                    this.TermsField = value;
                    this.RaisePropertyChanged("Terms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Updated {
            get {
                return this.UpdatedField;
            }
            set {
                if ((this.UpdatedField.Equals(value) != true)) {
                    this.UpdatedField = value;
                    this.RaisePropertyChanged("Updated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Media", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.Services.NewYorkTimes")]
    [System.SerializableAttribute()]
    internal partial class Media : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CopyRight {
            get {
                return this.CopyRightField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyRightField, value) != true)) {
                    this.CopyRightField = value;
                    this.RaisePropertyChanged("CopyRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubType {
            get {
                return this.SubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypeField, value) != true)) {
                    this.SubTypeField = value;
                    this.RaisePropertyChanged("SubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewYorkTimesServices.INewYorkTimes")]
    internal interface INewYorkTimes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/BestSellerLists", ReplyAction="http://tempuri.org/INewYorkTimes/BestSellerListsResponse")]
        System.Collections.Generic.List<string> BestSellerLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/BestSellers", ReplyAction="http://tempuri.org/INewYorkTimes/BestSellersResponse")]
        System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.BestSeller> BestSellers(string List, System.DateTime publicationdate, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/MovieReviews", ReplyAction="http://tempuri.org/INewYorkTimes/MovieReviewsResponse")]
        void MovieReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/TodaysNewsWire", ReplyAction="http://tempuri.org/INewYorkTimes/TodaysNewsWireResponse")]
        System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.NewsWire> TodaysNewsWire(int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/RecentNewsWire", ReplyAction="http://tempuri.org/INewYorkTimes/RecentNewsWireResponse")]
        System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.NewsWire> RecentNewsWire(int offset, int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface INewYorkTimesChannel : LigoSoftware.NewYorkTimesServices.INewYorkTimes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal partial class NewYorkTimesClient : System.ServiceModel.ClientBase<LigoSoftware.NewYorkTimesServices.INewYorkTimes>, LigoSoftware.NewYorkTimesServices.INewYorkTimes {
        
        public NewYorkTimesClient() {
        }
        
        public NewYorkTimesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewYorkTimesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewYorkTimesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewYorkTimesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> BestSellerLists() {
            return base.Channel.BestSellerLists();
        }
        
        public System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.BestSeller> BestSellers(string List, System.DateTime publicationdate, int offset) {
            return base.Channel.BestSellers(List, publicationdate, offset);
        }
        
        public void MovieReviews() {
            base.Channel.MovieReviews();
        }
        
        public System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.NewsWire> TodaysNewsWire(int offset, int count) {
            return base.Channel.TodaysNewsWire(offset, count);
        }
        
        public System.Collections.Generic.List<LigoSoftware.NewYorkTimesServices.NewsWire> RecentNewsWire(int offset, int count) {
            return base.Channel.RecentNewsWire(offset, count);
        }
    }
}
