//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crimson.Catalog.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatalogSites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogSites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crimson.Catalog.Services.Resources.CatalogSites", typeof(CatalogSites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com|http://webservices.amazon.com/onca/xml?Service=AWSECommerceService&amp;AWSAccessKeyId={0}&amp;tag={1}Operation=ItemSearch&amp;SearchIndex={2}&amp;ResponseGroup=Medium&amp;|WebService.
        /// </summary>
        internal static string Amazon {
            get {
                return ResourceManager.GetString("Amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ligosoftware.com|http://www.ligosoftware.com|Webservice.
        /// </summary>
        internal static string CrimsonCatalog {
            get {
                return ResourceManager.GetString("CrimsonCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://gutenberg.net.au|http://gutenberg.net.au/pga-Australiana-marc.zip|MARC.
        /// </summary>
        internal static string GutenburgAustralia {
            get {
                return ResourceManager.GetString("GutenburgAustralia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://pge.rastko.net/|http://pge.rastko.net/feeds/catalog.rdf.zip|RDT.
        /// </summary>
        internal static string GutenBurgEurope {
            get {
                return ResourceManager.GetString("GutenBurgEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.gutenberg.org|http://www.gutenberg.org/feeds/catalog.rdf.zip|RDF.
        /// </summary>
        internal static string GutenBurgUS {
            get {
                return ResourceManager.GetString("GutenBurgUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.loc..gov|http://z3950.loc.gov:7090/voyager?version=1.1&amp;operation=searchRetrieve&amp;maximumRecords=50&amp;recordSchema=dc&amp;query=|DublinCore.
        /// </summary>
        internal static string LibraryofCongress {
            get {
                return ResourceManager.GetString("LibraryofCongress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Library|MyLibrary.sdf|SQLCE Database.
        /// </summary>
        internal static string LocalCatalog {
            get {
                return ResourceManager.GetString("LocalCatalog", resourceCulture);
            }
        }
    }
}
