//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crimson.WinReader.NewYorkTimes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestSeller", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.NewYorkTimes")]
    [System.SerializableAttribute()]
    public partial class BestSeller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewsWire", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.NewYorkTimes")]
    [System.SerializableAttribute()]
    public partial class NewsWire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlogNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ByLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriesTagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexingTermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KickerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Crimson.WinReader.NewYorkTimes.Media[] MediaItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubHeadlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlogName {
            get {
                return this.BlogNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogNameField, value) != true)) {
                    this.BlogNameField = value;
                    this.RaisePropertyChanged("BlogName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ByLine {
            get {
                return this.ByLineField;
            }
            set {
                if ((object.ReferenceEquals(this.ByLineField, value) != true)) {
                    this.ByLineField = value;
                    this.RaisePropertyChanged("ByLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriesTags {
            get {
                return this.CategoriesTagsField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesTagsField, value) != true)) {
                    this.CategoriesTagsField = value;
                    this.RaisePropertyChanged("CategoriesTags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyRight {
            get {
                return this.CopyRightField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyRightField, value) != true)) {
                    this.CopyRightField = value;
                    this.RaisePropertyChanged("CopyRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Headline {
            get {
                return this.HeadlineField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadlineField, value) != true)) {
                    this.HeadlineField = value;
                    this.RaisePropertyChanged("Headline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndexingTerms {
            get {
                return this.IndexingTermsField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexingTermsField, value) != true)) {
                    this.IndexingTermsField = value;
                    this.RaisePropertyChanged("IndexingTerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kicker {
            get {
                return this.KickerField;
            }
            set {
                if ((object.ReferenceEquals(this.KickerField, value) != true)) {
                    this.KickerField = value;
                    this.RaisePropertyChanged("Kicker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Crimson.WinReader.NewYorkTimes.Media[] MediaItems {
            get {
                return this.MediaItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaItemsField, value) != true)) {
                    this.MediaItemsField = value;
                    this.RaisePropertyChanged("MediaItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organizations {
            get {
                return this.OrganizationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationsField, value) != true)) {
                    this.OrganizationsField = value;
                    this.RaisePropertyChanged("Organizations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string People {
            get {
                return this.PeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleField, value) != true)) {
                    this.PeopleField = value;
                    this.RaisePropertyChanged("People");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform {
            get {
                return this.PlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                    this.PlatformField = value;
                    this.RaisePropertyChanged("Platform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedUrl {
            get {
                return this.RelatedUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedUrlField, value) != true)) {
                    this.RelatedUrlField = value;
                    this.RaisePropertyChanged("RelatedUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Section {
            get {
                return this.SectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionField, value) != true)) {
                    this.SectionField = value;
                    this.RaisePropertyChanged("Section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubHeadline {
            get {
                return this.SubHeadlineField;
            }
            set {
                if ((object.ReferenceEquals(this.SubHeadlineField, value) != true)) {
                    this.SubHeadlineField = value;
                    this.RaisePropertyChanged("SubHeadline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSection {
            get {
                return this.SubSectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubSectionField, value) != true)) {
                    this.SubSectionField = value;
                    this.RaisePropertyChanged("SubSection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubType {
            get {
                return this.SubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypeField, value) != true)) {
                    this.SubTypeField = value;
                    this.RaisePropertyChanged("SubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terms {
            get {
                return this.TermsField;
            }
            set {
                if ((object.ReferenceEquals(this.TermsField, value) != true)) {
                    this.TermsField = value;
                    this.RaisePropertyChanged("Terms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Updated {
            get {
                return this.UpdatedField;
            }
            set {
                if ((this.UpdatedField.Equals(value) != true)) {
                    this.UpdatedField = value;
                    this.RaisePropertyChanged("Updated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Media", Namespace="http://schemas.datacontract.org/2004/07/Crimson.Catalog.NewYorkTimes")]
    [System.SerializableAttribute()]
    public partial class Media : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyRight {
            get {
                return this.CopyRightField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyRightField, value) != true)) {
                    this.CopyRightField = value;
                    this.RaisePropertyChanged("CopyRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubType {
            get {
                return this.SubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypeField, value) != true)) {
                    this.SubTypeField = value;
                    this.RaisePropertyChanged("SubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewYorkTimes.INewYorkTimes")]
    public interface INewYorkTimes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/BestSellerLists", ReplyAction="http://tempuri.org/INewYorkTimes/BestSellerListsResponse")]
        string[] BestSellerLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/BestSellers", ReplyAction="http://tempuri.org/INewYorkTimes/BestSellersResponse")]
        Crimson.WinReader.NewYorkTimes.BestSeller[] BestSellers(string List, System.DateTime publicationdate, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/MovieReviews", ReplyAction="http://tempuri.org/INewYorkTimes/MovieReviewsResponse")]
        void MovieReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/TodaysNewsWire", ReplyAction="http://tempuri.org/INewYorkTimes/TodaysNewsWireResponse")]
        Crimson.WinReader.NewYorkTimes.NewsWire[] TodaysNewsWire(int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewYorkTimes/RecentNewsWire", ReplyAction="http://tempuri.org/INewYorkTimes/RecentNewsWireResponse")]
        Crimson.WinReader.NewYorkTimes.NewsWire[] RecentNewsWire(int offset, int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface INewYorkTimesChannel : Crimson.WinReader.NewYorkTimes.INewYorkTimes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class NewYorkTimesClient : System.ServiceModel.ClientBase<Crimson.WinReader.NewYorkTimes.INewYorkTimes>, Crimson.WinReader.NewYorkTimes.INewYorkTimes {
        
        public NewYorkTimesClient() {
        }
        
        public NewYorkTimesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewYorkTimesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewYorkTimesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewYorkTimesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] BestSellerLists() {
            return base.Channel.BestSellerLists();
        }
        
        public Crimson.WinReader.NewYorkTimes.BestSeller[] BestSellers(string List, System.DateTime publicationdate, int offset) {
            return base.Channel.BestSellers(List, publicationdate, offset);
        }
        
        public void MovieReviews() {
            base.Channel.MovieReviews();
        }
        
        public Crimson.WinReader.NewYorkTimes.NewsWire[] TodaysNewsWire(int offset, int count) {
            return base.Channel.TodaysNewsWire(offset, count);
        }
        
        public Crimson.WinReader.NewYorkTimes.NewsWire[] RecentNewsWire(int offset, int count) {
            return base.Channel.RecentNewsWire(offset, count);
        }
    }
}
