//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crimson.Catalog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _12BooksThatChangedTheWorld {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _12BooksThatChangedTheWorld() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crimson.Catalog.Resources.12BooksThatChangedTheWorld", typeof(_12BooksThatChangedTheWorld).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principia Mathematica|Isaac Newton.
        /// </summary>
        internal static string Book0 {
            get {
                return ResourceManager.GetString("Book0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married Love|Marie Stopes.
        /// </summary>
        internal static string Book1 {
            get {
                return ResourceManager.GetString("Book1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Inquiry into the Nature and Causes of the Wealth of Nations|Adam Smith.
        /// </summary>
        internal static string Book10 {
            get {
                return ResourceManager.GetString("Book10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Folio|William Shakespeare.
        /// </summary>
        internal static string Book11 {
            get {
                return ResourceManager.GetString("Book11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magna Carta.
        /// </summary>
        internal static string Book2 {
            get {
                return ResourceManager.GetString("Book2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book of Rules of Association Football.
        /// </summary>
        internal static string Book3 {
            get {
                return ResourceManager.GetString("Book3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Origin of Species|Charles Darwin.
        /// </summary>
        internal static string Book4 {
            get {
                return ResourceManager.GetString("Book4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Abolition of the Slave Trade|William Wilberforce.
        /// </summary>
        internal static string Book5 {
            get {
                return ResourceManager.GetString("Book5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Vindication of the Rights of Woman|Mary Wollstonecraft.
        /// </summary>
        internal static string Book6 {
            get {
                return ResourceManager.GetString("Book6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Researches in Electricity|Michael Faraday.
        /// </summary>
        internal static string Book7 {
            get {
                return ResourceManager.GetString("Book7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patent specification for Arkwright’s Spinning Machine|Richard Arkwright.
        /// </summary>
        internal static string Book8 {
            get {
                return ResourceManager.GetString("Book8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The King James Bible|William Tyndale and others.
        /// </summary>
        internal static string Book9 {
            get {
                return ResourceManager.GetString("Book9", resourceCulture);
            }
        }
    }
}
